server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.95.196.58:3306/dormroom?useUnicode=true&characterEncoding=UTF-8
    username: dormroom
    password: dormroom
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  jmx:
    enabled: false #一个tomcat下多个springboot项目需要配置这个  不然报错


logging:
  level:
    vip.bzsy: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #扫描xml
  type-aliases-package: vip.bzsy.model #javabeen
  global-config:
    db-config: #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0


audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY
  name: dormroomyadmin
  expiresSecond: 720000000

SALT: dormroom
PASS_COUNT: 10

