server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://47.95.196.58:3306/tally?useUnicode=true&characterEncoding=UTF-8
    username: tally
    password: tally
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource

logging:
  level:
    vip.bzsy: debug

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml  #扫描xml
  type-aliases-package: vip.bzsy.model #javabeen
  global-config:
    db-config: #逻辑删除
      logic-delete-value: 1
      logic-not-delete-value: 0


audience:
  clientId: 098f6bcd4621d373cade4e832627b4f6
  base64Secret: MDk4ZjZiY2Q0NjIxZDM3M2NhZGU0ZTgzMjYyN2I0ZjY
  name: tallyadmin
  expiresSecond: 720000000

SALT: tally
PASS_COUNT: 10
APP_ID: 15841148
API_KEY: yC3gY9zrZlWuMFmBqB9ga0NB
SECRET_KEY: N0YEQGPQIVQv46ReUCowpURn2UCsiOQR